name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root dependencies (if any)
        run: |
          if [ -f package-lock.json ]; then npm ci; fi

      - name: Install and build client
        working-directory: client
        run: |
          npm ci
          npm run build --if-present

      - name: Install server dependencies
        working-directory: server
        run: |
          npm ci
          npm run build --if-present

      - name: Validate server starts (dry)
        working-directory: server
        run: |
          node -e "require('fs').existsSync('index.js') && console.log('index.js present')"


